acceptance/setup/install_pe.rb
acceptance/setup/install_puppet.rb

based on work in https://github.com/puppetlabs/puppetlabs-concat/blob/master/spec/spec_helper_acceptance.rb#L29-L30

Modify the way we install stdlib due to github rpc hangups

---

README.markdown

1. Remove any "what this affects" sections, except where particularly warranted.
2. Make sure that for each parameter, where applicable, there is a data type and a default value.
3. Make sure that for each parameter that's applicable, there is a note if the parameter is optional.
4. Make sure the links in the README work and are accurate.
5. Update the link in the Contributing section to point here: https://docs.puppetlabs.com/forge/contributing.html
6. General copyediting.

Updates README file per DOC-1492

---

CHANGELOG.md
metadata.json

- CHANGELOG and metadata update

(MODULES-3340) Release 1.1.2

---

Gemfile

The PR contains the updates from the new modsync config for windows;
- LICENSE, NOTICE, CONTRIBUTING, MAINTAINERS updates (where applicable)
- Gemfile, Appveyor, Travis, gitignore cleanup
https://github.com/puppetlabs/modulesync_configs/pull/66
https://github.com/puppetlabs/modulesync_configs/pull/63
https://github.com/puppetlabs/modulesync_configs/pull/62
https://github.com/puppetlabs/modulesync_configs/pull/61

(maint) modsync update - master

---

CHANGELOG.md
CONTRIBUTING.md
README.markdown
metadata.json

Update all references from puppetlabs to puppet

(MODULES-3356) Branding Name Change

---

CHANGELOG.md
README.markdown
metadata.json

(MODULES-4455) Prepare for release 1.1.4

---

.travis.yml

(maint) - modulesync 1d81b6a

---

CHANGELOG.md
metadata.json

(MODULES-6411) Release prep for 2.0.0

---

CHANGELOG.md
metadata.json

Mergeback release into master

---

CHANGELOG.md
metadata.json

This commit updates the module for a version 2.0.2 release.

(MODULES-7564) Prepare module for 2.0.2 release

---

CHANGELOG.md
metadata.json

(MODULES-7564) Mergeback after 2.0.2 Release

---

CHANGELOG.md
metadata.json

This commit updates the module in prepartion for a v2.1.0 release.

(MODULES-8048) Release prep for 2.1.0

---

CHANGELOG.md
metadata.json

(MODULES-8048) - 2.1.0 Mergeback

---

spec/unit/puppet/provider/registry_key_spec.rb
spec/unit/puppet/provider/registry_value_spec.rb

to facilitate more complete test output from our unit tests.

(WIN-280) add skip() unless pattern to unit tests

---

metadata.json

Updating windows versions to be inline with formatting of other supported modules

(maint) - Updating windows versions

---

examples/compliance_example.pp
examples/purge_example.pp
examples/registry_examples.pp
examples/service_example.pp
spec/fixtures/mixed_default_settings/manifests/init.pp

Small fixes to the examples to allow the puppet lint checks to pass

(maint) - Lint Fixes

---

.github/pull_request_template.md
.github/workflows/release.yml
.github/workflows/weekly.yml
CHANGELOG.md
CONTRIBUTING.md
HISTORY.md
README.md
REFERENCE.md
manifests/service.pp
manifests/value.pp
metadata.json

Removal of any offensive or inappropriate terminology from the code base.

(IAC-1004) - Removal of inappropriate terminology

---

.github/workflows/nightly.yml
.github/workflows/pr_test.yml

Request for a review
Update service url

(maint) update service url

---

CHANGELOG.md
metadata.json

(maint) Release Merge Back PR version 3.2.0

---

.github/workflows/nightly.yml
.puppet-lint.rc
.sync.yml
Rakefile
examples/compliance_example.pp
examples/purge_example.pp
examples/registry_examples.pp
examples/service_example.pp
manifests/service.pp
manifests/value.pp
metadata.json

(Maint) PDK Update
pdk version: `2.3.0`

pdksync - (Maint) PDK Update

---

.puppet-lint.rc
.sync.yml
Rakefile
examples/compliance_example.pp
examples/purge_example.pp
examples/registry_examples.pp
manifests/service.pp
manifests/value.pp
spec/acceptance/registry_management_spec.rb
spec/defines/value_spec.rb

Code now compliant with rules regarding:
parameter types
parameter documentation
top scope facts
legacy facts
relative classname inclusion
unquoted string in case
unquoted string in selector

(CONT-362) Syntax update

---

lib/puppet/provider/registry_key/registry.rb
lib/puppet/provider/registry_value/registry.rb

updated legacy facts with their latest counterpart

(CAT-2212) Remove legacy facts
