puppetlabs/puppetlabs-registry

- Gemfile
The version of Puppet/Facter/Hiera will determine the exact versions
of the Windows gems, so relax the versioning a bit to allow for the
proper versions of gems to be pulled in.
There is no need to get super specific on x86 versus x64, the Puppet
gem will determine the exact version (based on that we were shipping
x64 versions of Puppet with the proper dependencies, so we're not
subject to the issues that were present when we didn't have Windows
specific Puppet gems).
> (maint) Relax gem dependencies for Windows

- appveyor.yml
- Setup a matrix with:
- Ruby 2.1 and Puppet 4.x (latest) and
- Ruby 2.0 x64 / Ruby 1.9.3 x86 + Puppet 3.x (latest)
- Ruby 1.9.3 x86 + Puppet 3.3.2 (oldest supported)
This has some content from #82 that should be removed when that PR is rebased / updated. //cc @cyberious
> (maint) add AppVeyor support

- spec/unit/puppet/provider/registry_value_spec.rb
- As it turns out, the previous test for a well known value
would fail under Windows 2003, because the value is SYSTEM
instead of System.  We could adjust the case, but instead
perform a match of a given key to an environment variable
that should match it to rule out OS specific casing issues.
> (maint) fix registry_value provider spec fail

- .sync.yml
- Gemfile
Further restrict down the restrictions on windows dependencies when
using older Puppet versions, such that it works with Puppet 3.0.0 -
3.7.0. It does require a bit more logic in selecting gems but it allows
for testing older platforms without any additional known issues for
Puppet versions under 3.4.0.
> (MODULES-2207) Gem restrictions for Older puppet versions

- acceptance/setup/install_pe.rb
- acceptance/setup/install_puppet.rb
- acceptance/tests/resource/registry/should_manage_values.rb
- Beakers shell function always uses the default node, which is
undesirable for installing stdlib
- The x64? check in should_manage_values should be using the bitness
of the node under test, not the default node
> (maint) Multiple node acceptance fixes

- lib/puppet/provider/registry_value/registry.rb
- lib/puppet_x/puppetlabs/registry/provider_base.rb
- spec/unit/puppet/provider/registry_value_spec.rb
- The Ruby implementation of write is buggy at :
https://github.com/ruby/ruby/blob/v2_1_6/ext/win32/lib/win32/registry.rb#L727-L748
When writing a REG_MULTI_SZ, the MSDN documentation for RegSetValueEx
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724923(v=vs.85).aspx
states that for the lpData parameter that "With the REG_MULTI_SZ data
type, the string must be terminated with two null characters."  It
further states for the cbData parameter that "The size of the
information pointed to by the lpData parameter, in bytes. If the data
is of type REG_SZ, REG_EXPAND_SZ, or REG_MULTI_SZ, cbData must include
the size of the terminating null character or characters."
Looking at the implementation, we can see that the length for a
REG_MULTI_SZ is calculated properly, but the second …
> (MODULES-1921) Ruby registry writes corrupt string

- lib/puppet/provider/registry_value/registry.rb
- spec/unit/puppet/provider/registry_value_spec.rb
- In 0b99718bc7 a helper method to_byte_array was introduced to convert
a numeric value into a properly padded byte array.  Unfortunately
that introduced an error as the byte array ordering was incorrect.
This has caused DWORD and QWORD values to be written wrong.
For instance, creating a native (little) endian string from a large
32-bit value (4294967294) should yield the following bytes:
pry(main)> [2**32-2].pack('L').unpack('C*')
=> [254, 255, 255, 255]
That can be further round-tripped with .pack('C*').unpack('L*')[0]
However, using to_bytes_array, the bytes come back improperly ordered
pry(main)> to_byte_array(2**32-2, 4)
=> [255, 255, 255, 254]
pry(main)> [255, 255, 255, 254].pack('C*').unpack('L*')[0]
=> 4278190079
As a result, because of the improper ordering of bytes, the wrong …
> (MODULES-2409) Endian-ness incorrect for DWORD and QWORD

- .gitignore
- .sync.yml
- .travis.yml
- Gemfile
- appveyor.yml
- spec/spec_helper.rb
- spec/unit/puppet/provider/registry_key_spec.rb
- spec/unit/puppet/provider/registry_value_spec.rb
- spec/unit/puppet/type/registry_key_spec.rb
Beaker needs a version of Rake less than 11 due to using
`last_comment' in rake_task.rb:62. Reduce the version of
Rake down to the same dependency that Beaker does as a
development dependency.
Rspec 3+ requires that should be explicitly set as an expect term.
be_true and be_false have also been changed so that they are not
whether something is truthy or falsey, but simply really true/false. To
get the older behavior, the test simply needs to check for be_truthy or
be_falsey. For explicit true/false checks, it is be true and be false.
Remove gem install bundler as part of modulesync updates.
Paired with Glenn Sarti <glenn.sarti at puppetlabs dot com>
> (FM-4917) Rake / Beaker / Rspec compatibility

- manifests/value.pp
Prior to this, the parameters in the defined type, registry::value, were
all on one line and not spaced according to the Puppet Labs style guide.
This commit fixes that by putting each parameter on its own line and
lining everything up.
> (maint) Fix the style of the registry::value parameters

- manifests/service.pp
This is no longer a valid bareword.
> (MODULES-4331) quoted UNSET string

- README.markdown
Previously the registry_value type stated that it created parent keys
if they did not exist, however this is not true.  This commit updates the text
to indicate that if the parent keys do not exist an error will raised, and a
recommendation to use the registry_key to ensure the parent keys exist first.
This commit also reformats the markdown so that there is a single space between
the header hashes and the text as per Puppet markdown guidelines.
[skip ci]
> (MODULES-4446) Modify README and update the registry_value type

- metadata.json
This commit constrains the stdlib dependency so that it is not open ended anymore
> (MODULES-5157) Constrain stdlib dependency

- Rakefile
The acceptance tests for Registry are written in standard beaker format however
the preferred method is using beaker-rspec.  This commit overrides the
default `beaker` task, which would normally use beaker-rspec, and instead
invokes beaker directly.  This is only need while the module tests are migrated
to the newer rspec-beaker format.
> (maint) Modify beaker rake task to invoke beaker directly

- .fixtures.yml
- lib/puppet_x/puppetlabs/registry.rb
- spec/classes/mixed_default_settings_spec.rb
- spec/fixtures/mixed_default_settings/manifests/init.pp
- spec/unit/puppet/provider/registry_value_spec.rb
- spec/unit/puppet/type/registry_key_spec.rb
- spec/unit/puppet/type/registry_value_spec.rb
Previously the tests for the registry_value type were incomplete or were not
testing what they said they were.  This commit;
* Adds a compile test for when one resource is setting a default value and
another is not, but shares the same name.  A fix for this was implemented
in 64bba67 however there were no tests for this behaviour
* Fixed a bug in the canonicalising of path names which would append a backslash
every time the method was called
* Actually tested that multiple backslashes are removed on the path
* Raised errors when an non default, but root only path was passed into a
registry value.  This is different to registry keys, where this is allowed.
* Added tests for autorequiring of registry_key from registry_value resources
* Added tests in the registry_value provider for creating …
> (MODULES-2957) Fix registry_value tests

- lib/puppet_x/puppetlabs/registry.rb
- Some constants appearing in class methods were guarded as they're
only available on Windows platforms. However, since these constants
appear in methods that are never touched in specs on non-Windows
platforms, the guard is unnecessary.
- Existing code has a heuristic for string splitting that can be
mapped to simpler code. Giving existing test coverage, no additional tests should be necessary.
- Previous code entered a flow that made little sense, given paths
without at least a single \ are unsupported.
For instance, `hklm` is invalid, but `hklm\` is considered valid per the documentation inside specs of type\registry_value_spec.rb at https://github.com/puppetlabs/puppetlabs-registry/blob/master/spec/unit/puppet/type/registry_value_spec.rb#L47-L51
Raising an error was deferred …
> (MODULES-2957) Simplify code from merge of PR #146

- CHANGELOG.md
Prior to this commit the windows team was not tracking
changes prior to release in the changelog. Per the
KeepAChangelog standard, using an unreleased section
provides value to the users and developers both.
Using this section will make release prep easier and
allow users who want to leverage the module from master
to do so with clear knowledge of what changes have
been made to the code since the last release.
This commit adds the unreleased section to the CHANGELOG
and adds notes for the changes.
> (MAINT) Convert CHANGELOG to KAC standard

- CHANGELOG.md
- manifests/value.pp
- spec/defines/value_spec.rb
- Demonstrate the bug introduced in the 2.0.0 release as part of
48a0b07
- Tests for dword, qword and array type values currently fail in the first 
commit given the defined type doesn't properly type the $data value to
allow numeric values or arrays.
- Fix the bug introduced in 48a0b07
that did not have lenient enough typing for the $data parameter to
the registry::value defined type.
- This commit adds support for numerics, which are necessary for
dword and qword. It also adds support for arrays, which are always
an array of strings (corresponding to REG_MULTI_SZ).
> (MODULES-6528) Fix registry::value defined type

- manifests/value.pp
- The Variant in Array[Variant[String]] is completely unnecessary
and can be simplified to Array[String]
> (maint) Simplify registry::value type definition

- lib/puppet/type/registry_key.rb
- lib/puppet/type/registry_value.rb
This change will fix errors when running `puppet generate types`
Errors:
```
Error: /etc/puppetlabs/code/environments/production/modules/registry/lib/puppet/type/registry_key.rb: title patterns that use procs are not supported.
Error: /etc/puppetlabs/code/environments/production/modules/registry/lib/puppet/type/registry_value.rb: title patterns that use procs are not supported.
```
> (MODULES-6818) Fix types to no longer use unsupported proc title patterns

- spec/spec_helper_acceptance.rb
Previously the spec helper would only install the registry module on Windows
platforms however when testing master-agent scenarios, the module must also
exist on the non-Windows master.  This commit updates the spec helper to install
the module onto all hosts, not just Windows platforms.
> (FM-6934) Update acceptance tests for master-agent scenario

- lib/puppet/type/registry_key.rb
- spec/unit/puppet/type/registry_key_spec.rb
Previously when the `purge_values` parameter was set to true, it would fail on
registry values which contained an uppercase name, and already exsts.  This was
due to the array comparison using `.downcase` for the is_value elements, but
not doing the same for the should_values elements.
This commit changes the should_values elements to always be downcased thereby
making the later comparison valid.  This commit also updates the tests, which
would now fail if the fix was not applied.
> (MODULES-7534) Use case insensitive search when purging

- .sync.yml
The .sync.yml file had an errant comment in the file.  This commit removes the text as it has no affect.
> (maint) Remove redundant comment in .sync.yml

- .sync.yml
- Gemfile
- appveyor.yml
- metadata.json
- spec/defines/value_spec.rb
This commit updates the metadata to show support for Puppet 6.
> (MODULES-7832) Update metadata for Puppet 6

- lib/puppet/provider/registry_value/registry.rb
- lib/puppet/type/registry_value.rb
- spec/unit/puppet/type/registry_value_spec.rb
Previously it possible to pass in empty strings into REG_MULTI_SZ
registry types, however according to the Microsoft documentation [1]
this is not allowed.
This commit modifies the registry_value type to validate incoming
array infomration and to fail if this data is passed through.
This commit also adds tests for these scenarios.
[1] https://docs.microsoft.com/en-us/windows/desktop/sysinfo/registry-value-types
> (MODULES-5625) Fail on empty strings in REG_MULTI_SZ

- metadata.json
This commit updates the metadata so that rather than pointing at
a non-existent URL -- which was redirecting folks to the main
puppet.com page -- it now points at the github repository for the
project, just like virtually all of our other modules.
> MODULES-9802 Repair broken project url to point at repo

- .rubocop.yml
- .sync.yml
- Gemfile
- HISTORY.md
- Rakefile
- appveyor.yml
- lib/puppet/provider/registry_key/registry.rb
- lib/puppet_x/puppetlabs/registry.rb
- metadata.json
- spec/acceptance/should_create_key_spec.rb
- spec/acceptance/should_have_defined_type_spec.rb
- spec/acceptance/should_manage_values_spec.rb
- spec/unit/puppet/provider/registry_key_spec.rb
- spec/unit/puppet/provider/registry_value_spec.rb
- spec/unit/puppet/type/registry_key_spec.rb
- spec/unit/puppet/type/registry_value_spec.rb
- spec/watchr.rb
PR add's support for Changelog Generator. PDK Sync had to be done manually due to unique code within the rakefile.
> (maint) - Add support for Changelog Generator

- lib/puppet/provider/registry_value/registry.rb
Early ruby versions did not handle wide terminators correctly and would sometime
read past the end of the string causing segfaults. To prevent that, puppet
started embedding a wide terminator within the string. So the ruby string 'hi'
would be encoded as the three character string 'hi\0', and then that would be
encoded as UTF-16LE.
While this works, it creates ambiguity as to whether the "\0" character is part
of the data or not. For example, "hi\n\0".chop is "hi\n" whereas "hi\n".chop is
"hi", and is probably what was intended.
Ruby has since fixed its wide terminator handling, and as of Puppet 7, the
`wide_string` method no longer embeds a terminator in the string. So update the
registry module to explicitly add the terminator(s) before calling
RegSetValueExW`.
> (IAC-967) Append null terminators since it is no longer part of the data

- lib/puppet/type/registry_value.rb
Previously, the validation procedures were occuring in the #munge
method. This was a problem because if #munge raises an exception, the
error displayed to the user is opaque. If the data input is not valid,
the error should be raised in the #validate method. This will ensure
that the output given to the user includes information about the class,
resource, and parameter which is in error.
> Add possibility to produce a detailed error message 

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
Support for Windows Server 2008 and 2008 R2 was removed. 
Support for Windows 7 and 8 was removed.
﻿
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Dropped support for Windows(7,8, 2008 Server and 2008 R2 Server)

- CHANGELOG.md
Prior to this commit, it was brought to light an error in PR naming for Puppet 8 support related PRs, where they failed to mention the potential drop in Puppet 6 support. This commit aims to fix the changelog so that it reflects better the changes made in this major update.
> (CONT-874) Update changelog
